# Generated by Django 4.0.4 on 2022-05-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='filelink_four',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='filelink_one',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='filelink_three',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='filelink_two',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
