# Generated by Django 4.0.4 on 2022-05-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_file_hoster_name1_article_file_hoster_name2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='File_hoster_name1',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='File_hoster_name2',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='File_hoster_name3',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='File_hoster_name4',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
