# Generated by Django 4.0.4 on 2022-05-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
